### ISSUE TITLE
Holiday Flair Banner promotion

### ISSUE THREAD

**Issue by CodeF53** [Martinz64/remove-nitro#1]
![image](https://user-images.githubusercontent.com/37855219/206549126-d8c95bcb-507c-4dc3-9ca6-29f571dd3eae.png)
```css
[class^=userPopoutInner] > [class^=wrapper] > [class^=banner] {
  display: none;
}
```

![image](https://user-images.githubusercontent.com/37855219/206549858-048cada2-2483-40c4-a880-230a4dcdef40.png)
```css
/* Avatar decoration nitro promo in profiles */
[class^=limitedFeatureBorder] {
  display: none;
}
```
