### ISSUE TITLE
Custom Role Icon server boosting promo 

### ISSUE THREAD

**Issue by CodeF53** [Martinz64/remove-nitro#2]
![image](https://user-images.githubusercontent.com/37855219/206550528-8676600c-8860-4e81-812c-99f86d6d3798.png)

Couldn't find a selector for this that doesn't use `:has`, but just hide the "Learn more" button

**Comment by Martinz64** [comment]
Closest i can get is this:
```css
[class*="popoutContainer-"] > [class*="ctaButton-"]{
	display: none !important;
}
```
Let's hope ctaButton is not used anywhere else

**Comment by CodeF53** [comment]
For when we get Electron v21.0.0 in discord
```css
button[class^=ctaButton]:has(div>svg[class^=boosterBadge]) {
  display: none;
}
```
