### ISSUE TITLE
Hides Vencord Encrypt Message Button

### ISSUE THREAD

**Issue by CodeF53** [Martinz64/remove-nitro#3]
HTML for the button:
```html
<button aria-haspopup="dialog" aria-label="Encrypt Message" type="button" class="button-f2h6uQ lookBlank-21BCro colorBrand-I6CyqQ grow-2sR_-F" style="margin-right: 2px;"></button>
```

CSS that hides it:
```css
[class^="channelTextArea"] [class^="buttons-"] > button, /* Gift Button */
{ display: none !important; }
```
